version: '3'
services: 
  myapp:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - DB_USER=root
      - DB_PASSWORD=changeit
    networks: 
      - mynet
    depends_on:
      - mydb

  mydb:
    image: stackupiss/northwind-db:v1
    volumes:
      - myvol:/var/lib/mysql
    networks: 
      - mynet

networks:
  mynet:

volumes: 
  myvol: